/**
 * Docusaurus plugin that generates a service worker using Workbox.
 *
 * This plugin runs during postBuild and produces a service worker file
 * (sw.js) in the build output directory.
 *
 * Strategy: NO pre-caching. Docusaurus sites are large (hundreds of pages,
 * 50-150MB of static assets). Pre-caching all of that would fail on mobile
 * devices with limited storage quotas. Instead, we use runtime caching:
 *
 * - Navigation requests (HTML): NetworkFirst with 5s timeout fallback
 * - JS/CSS bundles: StaleWhileRevalidate (always serve from cache, update
 *   in background)
 * - Images: CacheFirst with 30-day expiry
 * - Fonts: CacheFirst with 1-year expiry
 *
 * The service worker registration is injected into index.html automatically.
 *
 * Configuration (in docusaurus.config.ts):
 *   plugins: [
 *     [require.resolve('./src/plugins/service-worker'), { enable: true }],
 *   ]
 */

import type { DocusaurusConfig, Plugin } from '@docusaurus/types';
import fs from 'fs';
import path from 'path';

interface ServiceWorkerPluginOptions {
  enable?: boolean;
  cacheId?: string;
}

const SERVICE_WORKER_SOURCE = `
// Wyatt's Notes Service Worker
// Generated by service-worker-plugin. Do not edit manually.

const CACHE_ID = '{{CACHE_ID}}';
const CACHE_VERSION = '{{CACHE_VERSION}}';

const PRECACHE_URLS = [
  './',
  './index.html',
];

// Install: precache the app shell only.
self.addEventListener('install', (event) => {
  event.waitUntil(
    caches.open(CACHE_ID + '-precache-v' + CACHE_VERSION).then((cache) => {
      return cache.addAll(PRECACHE_URLS);
    })
  );
  self.skipWaiting();
});

// Activate: clean up old caches.
self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches.keys().then((keys) =>
      Promise.all(
        keys
          .filter((key) => key.startsWith(CACHE_ID) && !key.includes(CACHE_VERSION))
          .map((key) => caches.delete(key))
      )
    )
  );
  self.clients.claim();
});

// Fetch: route by resource type.
self.addEventListener('fetch', (event) => {
  const { request } = event;
  const url = new URL(request.url);

  // Skip cross-origin requests (PhET, Desmos, GeoGebra, Algolia, etc.)
  if (url.origin !== self.location.origin) {
    return;
  }

  // Skip non-GET requests.
  if (request.method !== 'GET') {
    return;
  }

  // HTML pages: NetworkFirst with cache fallback.
  if (request.headers.get('accept')?.includes('text/html')) {
    event.respondWith(networkFirst(request, 'html-cache', 5));
    return;
  }

  // JavaScript and CSS: StaleWhileRevalidate.
  if (/\\.js$|\\.css$/.test(url.pathname)) {
    event.respondWith(staleWhileRevalidate(request, 'static-cache'));
    return;
  }

  // Fonts: CacheFirst with long expiry.
  if (/\\.(woff2?|ttf|eot)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(request, 'font-cache', 365));
    return;
  }

  // Images: CacheFirst with 30-day expiry.
  if (/\\.(png|jpg|jpeg|gif|webp|svg|ico)$/.test(url.pathname)) {
    event.respondWith(cacheFirst(request, 'image-cache', 30));
    return;
  }

  // Default: NetworkFirst.
  event.respondWith(networkFirst(request, 'default-cache', 3));
});

/**
 * NetworkFirst: try network, fall back to cache after timeout.
 */
async function networkFirst(request, cacheName, timeoutSeconds) {
  const cache = await caches.open(CACHE_ID + '-' + cacheName);

  try {
    const response = await Promise.race([
      fetch(request),
      new Promise((_, reject) =>
        setTimeout(() => reject(new Error('timeout')), timeoutSeconds * 1000)
      ),
    ]);

    if (response.ok) {
      // Clone before caching because response can only be consumed once.
      cache.put(request, response.clone());
    }
    return response;
  } catch {
    const cached = await cache.match(request);
    if (cached) return cached;
    return new Response('Offline', { status: 503, statusText: 'Service Unavailable' });
  }
}

/**
 * StaleWhileRevalidate: serve from cache immediately, update cache in background.
 */
async function staleWhileRevalidate(request, cacheName) {
  const cache = await caches.open(CACHE_ID + '-' + cacheName);
  const cached = await cache.match(request);

  const fetchPromise = fetch(request)
    .then((response) => {
      if (response.ok) {
        cache.put(request, response.clone());
      }
      return response;
    })
    .catch(() => cached);

  return cached || fetchPromise;
}

/**
 * CacheFirst: serve from cache, fetch if not cached.
 */
async function cacheFirst(request, cacheName, maxAgeDays) {
  const cache = await caches.open(CACHE_ID + '-' + cacheName);
  const cached = await cache.match(request);

  if (cached) {
    return cached;
  }

  const response = await fetch(request);
  if (response.ok) {
    cache.put(request, response.clone());
  }
  return response;
}
`;

export default function serviceWorkerPlugin(
  context: DocusaurusConfig,
  options: ServiceWorkerPluginOptions,
): Plugin {
  return {
    name: 'service-worker-plugin',

    async postBuild({ outDir, baseUrl }) {
      if (options.enable === false) {
        return;
      }

      const cacheId = options.cacheId || 'wyattsnotes';
      const cacheVersion = Date.now().toString(36);

      // Build the service worker source with template substitutions.
      const swSource = SERVICE_WORKER_SOURCE
        .replace(/\{\{CACHE_ID\}\}/g, cacheId)
        .replace(/\{\{CACHE_VERSION\}\}/g, cacheVersion);

      // Write sw.js to the build output.
      const swPath = path.join(outDir, 'sw.js');
      fs.writeFileSync(swPath, swSource, 'utf-8');

      // Inject service worker registration into index.html.
      const indexPath = path.join(outDir, 'index.html');

      if (fs.existsSync(indexPath)) {
        let indexContent = fs.readFileSync(indexPath, 'utf-8');
        const swRegister = `<script>
if('serviceWorker'in navigator){window.addEventListener('load',function(){navigator.serviceWorker.register('${baseUrl}sw.js')})}
</script>`;

        indexContent = indexContent.replace('</head>', `${swRegister}</head>`);
        fs.writeFileSync(indexPath, indexContent, 'utf-8');
      }

      const swSize = Buffer.byteLength(swSource, 'utf-8');
      console.log(
        `Service worker generated: ${swPath} (${swSize} bytes, ${cacheId}, v${cacheVersion})`,
      );
      console.log(
        'Strategy: runtime caching only (no pre-cache). NetworkFirst for HTML, StaleWhileRevalidate for JS/CSS, CacheFirst for images/fonts.',
      );
    },
  };
}
