import DOMPurify from 'dompurify';

/**
 * Sanitize HTML string using DOMPurify.
 * Defense-in-depth for dangerouslySetInnerHTML usage.
 * Allows safe HTML tags (p, strong, em, code, pre, ul, ol, li, etc.)
 * and math-related tags (span, sub, sup, math, mi, mn, mo, ms, mtext).
 */
export function sanitizeHtml(dirty: string): string {
  return DOMPurify.sanitize(dirty, {
    ALLOWED_TAGS: [
      // Block elements
      'p',
      'div',
      'br',
      'hr',
      // Inline elements
      'span',
      'strong',
      'b',
      'em',
      'i',
      'u',
      's',
      'mark',
      'small',
      'sub',
      'sup',
      'abbr',
      'code',
      'kbd',
      'var',
      'samp',
      // Headings
      'h1',
      'h2',
      'h3',
      'h4',
      'h5',
      'h6',
      // Lists
      'ul',
      'ol',
      'li',
      'dl',
      'dt',
      'dd',
      // Tables
      'table',
      'thead',
      'tbody',
      'tfoot',
      'tr',
      'th',
      'td',
      'caption',
      'colgroup',
      'col',
      // Code blocks
      'pre',
      'blockquote',
      // Math (KaTeX/MathJax)
      'math',
      'mi',
      'mn',
      'mo',
      'ms',
      'mtext',
      'mfrac',
      'msqrt',
      'mrow',
      'msup',
      'msub',
      'msubsup',
      'munder',
      'mover',
      'munderover',
      'mtable',
      'mtr',
      'mtd',
      'maligngroup',
      'malignmark',
      'annotation',
      'semantics',
      // SVG (Mermaid diagrams)
      'svg',
      'g',
      'path',
      'circle',
      'ellipse',
      'rect',
      'line',
      'polyline',
      'polygon',
      'text',
      'tspan',
      'textPath',
      'clipPath',
      'defs',
      'use',
      'image',
      'marker',
      'pattern',
      'linearGradient',
      'radialGradient',
      'stop',
      // Links
      'a',
    ],
    ALLOWED_ATTR: [
      // Global attributes
      'class',
      'id',
      'style',
      'title',
      'lang',
      'dir',
      'role',
      'aria-label',
      'aria-hidden',
      'aria-live',
      'aria-describedby',
      'aria-expanded',
      'data-testid',
      'data-*',
      // Links
      'href',
      'target',
      'rel',
      // Tables
      'colspan',
      'rowspan',
      'align',
      'valign',
      // Code
      'data-language',
      // Math
      'mathvariant',
      'mathsize',
      'mathcolor',
      'mathbackground',
      'displaystyle',
      'scriptlevel',
      'linethickness',
      'stretchy',
      'rowalign',
      'columnalign',
      'columnspacing',
      'rowspacing',
      'notation',
      'encoding',
      // SVG
      'viewBox',
      'xmlns',
      'width',
      'height',
      'x',
      'y',
      'rx',
      'ry',
      'd',
      'cx',
      'cy',
      'r',
      'x1',
      'y1',
      'x2',
      'y2',
      'dx',
      'dy',
      'fill',
      'stroke',
      'stroke-width',
      'stroke-dasharray',
      'opacity',
      'transform',
      'text-anchor',
      'dominant-baseline',
      'font-size',
      'font-family',
      'font-weight',
      'text-decoration',
      'points',
      'offset',
      'stop-color',
      'stop-opacity',
      'gradientUnits',
      'gradientTransform',
      'patternUnits',
      'markerWidth',
      'markerHeight',
      'refX',
      'refY',
      'orient',
      'clip-path',
      'marker-start',
      'marker-mid',
      'marker-end',
      'preserveAspectRatio',
      'flood-color',
      'flood-opacity',
      'id',
      'href',
      'xlink:href',
    ],
    ALLOW_DATA_ATTR: true,
    // Preserve SVG content (Mermaid diagrams produce complex SVGs)
    SANITIZE_DOM: true,
  });
}
