import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  alevelSidebar: [
    { type: 'autogenerated', dirName: 'biology' },
    { type: 'autogenerated', dirName: 'chemistry' },
    { type: 'autogenerated', dirName: 'computer-science' },
    { type: 'autogenerated', dirName: 'economics' },
  ],
};

export default sidebars;
