import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  alevelSidebar: [
    { type: 'autogenerated', dirName: 'biology' },
    { type: 'autogenerated', dirName: 'chemistry' },
    { type: 'autogenerated', dirName: 'computer-science' },
    { type: 'autogenerated', dirName: 'economics' },
    { type: 'autogenerated', dirName: 'english' },
    { type: 'autogenerated', dirName: 'geography' },
    { type: 'autogenerated', dirName: 'history' },
    { type: 'autogenerated', dirName: 'psychology' },
  ],
};

export default sidebars;
