import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  universitySidebar: [
    // Manual subject links — always visible, used primarily on the intro page
    // where the autogenerated section only shows intro.md.
    // Using 'link' type (not 'doc') because subjects live in separate plugins.
    {
      type: 'category',
      label: 'Subjects',
      items: [
        { type: 'link', label: 'Mathematics', href: '/docs/mathematics' },
        { type: 'link', label: 'Physics', href: '/docs/physics' },
        { type: 'link', label: 'Computing', href: '/docs/computing' },
        { type: 'link', label: 'Chemistry', href: '/docs/chemistry' },
        { type: 'link', label: 'Computer Science', href: '/docs/computer-science' },
        { type: 'link', label: 'Admissions', href: '/docs/admissions' },
      ],
    },
    // Autogenerated entries from each plugin's docs directory
    { type: 'autogenerated', dirName: '.' },
  ],
};

export default sidebars;
