import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  alevelSidebar: [
    { type: 'autogenerated', dirName: 'maths' },
    { type: 'autogenerated', dirName: 'further-maths' },
    { type: 'autogenerated', dirName: 'physics' },
  ],
};

export default sidebars;
