import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  alevelSidebar: [
    { type: 'autogenerated', dirName: 'biology' },
    { type: 'autogenerated', dirName: 'chemistry' },
    { type: 'autogenerated', dirName: 'computer-science' },
    { type: 'autogenerated', dirName: 'economics' },
    // english, geography, history, psychology excluded: SSG fails with
    // "Cannot read properties of undefined (reading 'id')" on _category_ pages.
    // TODO: investigate Docusaurus sidebar generation bug for nested directories.
    // { type: 'autogenerated', dirName: 'english' },
    // { type: 'autogenerated', dirName: 'geography' },
    // { type: 'autogenerated', dirName: 'history' },
    // { type: 'autogenerated', dirName: 'psychology' },
  ],
};

export default sidebars;
